'use client';

import { NextAuthProvider } from '@/app/provider';
import '../../globals.css'
import Script from 'next/script'

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {


    return (
        <html lang="en">
            <head>
                         <link rel="stylesheet" href="/assets/css/cryptoon.style.min.css" />
   
</head>


            <body  suppressHydrationWarning={true} >
                <div id="cryptoon-layout" className="theme-blue">

                    <div className="main p-2 py-3 p-xl-5">
                        {/* Body: Header */}
                        <div className="container-xxl">
                            {/* header rightbar icon */}
                            <div className="row align-items-center">
                                <div className="col">
                                    <a href="../index-2.html" className="d-flex align-item-center">
                                        <i className="fa fa-gg-circle fs-3" />
                                        <h5 className="mb-0 mt-1 mx-2">Cryptoon</h5>
                                    </a>
                                </div>
                                <div className="col-auto">
                                    <div className="d-flex align-item-center">


                                    </div>
                                </div>
                            </div>
                        </div>
                        <NextAuthProvider>
                               {children}
  </NextAuthProvider>

                     

                    </div>

                </div>
            </body>

            <Script src="/assets/bundles/libscripts.bundle.js" />
            {/* <Script src="/assets/bundles/apexcharts.bundle.js" /> */}
        </html >
    )
}
