
import '../../globals.css'
import Script from 'next/script'
import Header from '../../components/partials/header';
import Sidebar from '../../components/partials/sidebar';
import { NextAuthProvider } from '@/app/provider';
import { authOptions } from '@/app/lib/auth';
import { getServerSession } from 'next-auth';
import { redirect } from 'next/navigation';
import React from 'react';


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
  }) {
    const session = await getServerSession(authOptions);
  if (session == null || session === undefined) { 
    return redirect('/auth/login')
  }
 
  return (
    <html lang="en">
     {/* <link rel="stylesheet" href="assets/plugin/datatables/dataTables.bootstrap5.min.css" />  */}
      <head>
        <link rel="stylesheet" href="/assets/css/cryptoon.style.min.css" />
         {/* <link rel="stylesheet" href="/assets/plugin/jquery.steps/dist/jquery-steps.css" /> */}
  

    </head>
   
     
      <body  suppressHydrationWarning={true} >
        <div id="cryptoon-layout" className="theme-blue">


            <Sidebar />
              {/* main body area */}
            <div className="main px-lg-4 px-md-4">
                  
            <NextAuthProvider>
              <Header session={session} />
                               {
                                children
                              }
  </NextAuthProvider>
                 
            </div>
        </div>
      </body>
    
       <Script  src="/assets/bundles/libscripts.bundle.js" />
      
    </html>
  )
}
