'use client';
import '../../globals.css'
import Script from 'next/script'

import Header from '../../components/partials/header';
import { NextAuthProvider } from '@/app/provider';


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
  }) {
   

  return (
    <html lang="en">
     {/* <link rel="stylesheet" href="assets/plugin/datatables/dataTables.bootstrap5.min.css" />  */}
    
   
   <head>
                         <link rel="stylesheet" href="/assets/css/cryptoon.style.min.css" />
   
</head>
     
      <body  suppressHydrationWarning={true} >
        <div id="cryptoon-layout" className="theme-blue">


           
              {/* main body area */}
            <div className="main px-lg-4 px-md-4">
            <Header />
            
                   <NextAuthProvider>
                               {children}
  </NextAuthProvider>
                 
            </div>
        </div>
      </body>
    
       <Script  src="assets/bundles/libscripts.bundle.js" />
      <Script  src="assets/bundles/apexcharts.bundle.js" />
    </html>
  )
}
